import type { Instrument } from '@etoro/common/services';

export const mockAssets: Instrument[] = [
  {
    InstrumentID: 1001,
    InstrumentDisplayName: 'Apple',
    InstrumentTypeID: 5,
    ExchangeID: 4,
    Images: [
      {
        InstrumentID: 1001,
        Uri: 'https://etoro-cdn.etorostatic.com/market-avatars/1001/1001_494D5A_F7F7F7.svg',
        BackgroundColor: '#494D5A',
        TextColor: '#F7F7F7',
      },
    ],
    SymbolFull: 'AAPL',
    StocksIndustryID: 3,
    Price: 150.75,
    PriceChange: 1.25,
    PriceSource: 'NASDAQ',
    HasExpirationDate: false,
    IsInternalInstrument: false,
  },
  {
    InstrumentID: 1002,
    InstrumentDisplayName: 'Alphabet',
    InstrumentTypeID: 5,
    ExchangeID: 4,
    Images: [
      {
        InstrumentID: 1002,
        Uri: 'https://etoro-cdn.etorostatic.com/market-avatars/1002/1002_3183FF_F7F7F7.svg',
        BackgroundColor: '#3183FF',
        TextColor: '#F7F7F7',
      },
    ],
    SymbolFull: 'GOOG',
    StocksIndustryID: 8,
    Price: 2820.25,
    PriceChange: -12.25,
    PriceSource: 'NASDAQ',
    HasExpirationDate: false,
    IsInternalInstrument: false,
  },
  {
    InstrumentID: 1003,
    InstrumentDisplayName: 'Meta Platforms Inc',
    InstrumentTypeID: 5,
    ExchangeID: 4,
    Images: [
      {
        InstrumentID: 1003,
        Uri: 'https://etoro-cdn.etorostatic.com/market-avatars/1003/1003_F7F7F7_2C2C2C.svg',
        BackgroundColor: '#F7F7F7',
        TextColor: '#2C2C2C',
      },
    ],
    SymbolFull: 'META',
    StocksIndustryID: 8,
    Price: 384.25,
    PriceChange: 3.25,
    PriceSource: 'NASDAQ',
    HasExpirationDate: false,
    IsInternalInstrument: false,
  },
  {
    InstrumentID: 1004,
    InstrumentDisplayName: 'Microsoft',
    InstrumentTypeID: 5,
    ExchangeID: 4,
    Images: [
      {
        InstrumentID: 1004,
        Uri: 'https://etoro-cdn.etorostatic.com/market-avatars/1004/1004_F7F7F7_2C2C2C.svg',
        BackgroundColor: '#F7F7F7',
        TextColor: '#2C2C2C',
      },
    ],
    SymbolFull: 'MSFT',
    StocksIndustryID: 8,
    Price: 235.25,
    PriceChange: 4.25,
    PriceSource: 'NASDAQ',
    HasExpirationDate: false,
    IsInternalInstrument: false,
  },
  {
    InstrumentID: 1005,
    InstrumentDisplayName: 'Amazon.com Inc',
    InstrumentTypeID: 5,
    ExchangeID: 4,
    Images: [
      {
        InstrumentID: 1005,
        Uri: 'https://etoro-cdn.etorostatic.com/market-avatars/1005/1005_494D5A_F7F7F7.svg',
        BackgroundColor: '#494D5A',
        TextColor: '#F7F7F7',
      },
    ],
    SymbolFull: 'AMZN',
    StocksIndustryID: 7,
    Price: 3345.25,
    PriceChange: 5.25,
    PriceSource: 'NASDAQ',
    HasExpirationDate: false,
    IsInternalInstrument: false,
  },
];
