/* eslint-disable */
// AUTO-GENERATED — do not edit by hand.
// CDN asset format per illustration file, keyed by the flat filename stem
// `${name}_${size}_${theme}`. Formats are mixed: flat line art is `svg`, anything with a
// Figma `feTurbulence` stipple is `png` (not rendered by react-native-svg on native), and a
// few illustrations mix per theme (light `svg` / dark `png`).
import type { IllustrationFormat } from './api/types';

export const ILLUSTRATION_ASSET_FORMAT: Record<string, IllustrationFormat> = {
  assets_xxl_dark: 'png',
  assets_xxl_light: 'png',
  calendar_xxl_dark: 'png',
  calendar_xxl_light: 'svg',
  card_m_dark: 'svg',
  card_m_light: 'svg',
  connection_error_m_dark: 'png',
  connection_error_m_light: 'png',
  connection_error_xl_dark: 'png',
  connection_error_xl_light: 'png',
  coupon_s_dark: 'png',
  coupon_s_light: 'png',
  empty_bar_chart_m_dark: 'png',
  empty_bar_chart_m_light: 'png',
  empty_list_m_dark: 'png',
  empty_list_m_light: 'png',
  error_m_dark: 'png',
  error_m_light: 'png',
  error_xl_dark: 'png',
  error_xl_light: 'png',
  like_m_dark: 'svg',
  like_m_light: 'svg',
  magnifying_glass_m_dark: 'png',
  magnifying_glass_m_light: 'png',
  paper_plane_xxl_dark: 'png',
  paper_plane_xxl_light: 'svg',
  pending_m_dark: 'png',
  pending_m_light: 'png',
  pending_xl_dark: 'png',
  pending_xl_light: 'png',
  phone_coins_xxl_dark: 'png',
  phone_coins_xxl_light: 'svg',
  refer_a_friend_xxl_dark: 'png',
  refer_a_friend_xxl_light: 'svg',
  settings_m_dark: 'png',
  settings_m_light: 'png',
  shield_and_users_xxl_dark: 'png',
  shield_and_users_xxl_light: 'png',
  shield_checkmark_xxl_dark: 'svg',
  shield_checkmark_xxl_light: 'svg',
  shield_lock_xxl_dark: 'svg',
  shield_lock_xxl_light: 'svg',
  success_m_dark: 'png',
  success_m_light: 'png',
  success_xl_dark: 'png',
  success_xl_light: 'png',
  target_xxl_dark: 'png',
  target_xxl_light: 'svg',
  verify_xxl_dark: 'png',
  verify_xxl_light: 'svg',
  warning_m_dark: 'png',
  warning_m_light: 'png',
  warning_xl_dark: 'png',
  warning_xl_light: 'png',
};
