import {
  blue,
  blueOpacity,
  green,
  mint,
  mintOpacity,
  neutral,
  neutralOpacity,
  orange,
  orangeOpacity,
  purple,
  purpleOpacity,
  red,
  violet,
  violetOpacity,
  yellow,
  yellowOpacity,
} from '../../primitives';

const surfaceLight = {
  bgNeutralPrimary: neutral[0],
  bgNeutralSecondary: neutral[0],
  bgNeutralTertiary: neutral[0],
  bgNeutralQuaternary: neutral[0],
  bgNeutralQuinary: neutral[0],
  bgNeutralSenary: neutral[0],
  bgNeutralGreyPrimary: neutral[50],
  bgNeutralGreyPrimaryTransparent: neutralOpacity[50.0],
  bgNeutralGreySecondary: neutral[250],
  bgNeutralGreyQuinary: neutral[250],
  bgNeutralGreyQuaternary: neutral[250],
  bgNeutralGreySenary: neutral[300],
  bgNeutralDark: neutral[750],
  bgTransparentPrimary: neutralOpacity[0.85],
  bgBaseScrollPrimary: neutralOpacity[0.0],
  bgBaseScrollSecondary: neutralOpacity[0.0],
  bgBaseScrollTertiary: neutralOpacity[0.0],
  bgBaseScrollNeutralBright: neutralOpacity[0.0],
  bgTransparentPrimaryBright: neutralOpacity[0.25],
  bgTransparentSecondaryBright: neutralOpacity[0.15],
  bgGreyPrimary: neutral[100],
  bgGreySecondary: neutral[200],
  bgGreyTertiary: neutral[250],
  bgGreyTransparentPrimary: neutralOpacity[200.2],
  bgGreyTransparentSecondary: neutralOpacity[200.3],
  bgButtonGroupNormal: neutral[50],
  bgButtonGroupPressed: neutralOpacity[600.25],
  bgOverlayBase: neutralOpacity[950.0],
  bgOverlayTop: neutralOpacity[850.85],
  bgOverlayBottom: neutralOpacity[950.95],
  bgOverlayGeneral: neutralOpacity[0.25],
  bgNeutralPositive: green[100],
  bgNeutralNegative: red[50],
  bgOrangePrimary: orange[400],
  bgOrangeSecondary: orange[200],
  bgOrangeTertiary: orange[100],
  bgOrangeTransparentPrimary: orangeOpacity[500.2],
  bgOrangeTransparentSecondary: orangeOpacity[500.3],
  bgYellowPrimary: yellow[400],
  bgYellowSecondary: yellow[200],
  bgYellowTertiary: yellow[100],
  bgYellowTransparentPrimary: yellowOpacity[500.2],
  bgYellowTransparentSecondary: yellowOpacity[500.3],
  bgMintPrimary: mint[400],
  bgMintSecondary: mint[200],
  bgMintTertiary: mint[100],
  bgMintTransparentPrimary: mintOpacity[500.2],
  bgMintTransparentSecondary: mintOpacity[500.3],
  bgBluePrimary: blue[400],
  bgBlueSecondary: blue[300],
  bgBlueTertiary: blue[100],
  bgBlueTransparentPrimary: blueOpacity[500.2],
  bgBlueTransparentSecondary: blueOpacity[500.3],
  bgPurplePrimary: purple[400],
  bgPurpleSecondary: purple[300],
  bgPurpleTertiary: purple[100],
  bgPurpleTransparentPrimary: purpleOpacity[500.2],
  bgPurpleTransparentSecondary: purpleOpacity[500.3],
  bgVioletPrimary: violet[400],
  bgVioletSecondary: violet[300],
  bgVioletTertiary: violet[100],
  bgVioletTransparentPrimary: violetOpacity[500.2],
  bgVioletTransparentSecondary: violetOpacity[500.3],
  // TODO: change to liquid glass
  bgGlassPrimaryOverlay: neutral[0],

  bgDarkSurface: neutral[800],
  bgLightSurface: neutral[600],

  // gradients
  bgOrangeGradient70: orange[700],
  bgOrangeGradient50: orange[500],
  bgYellowGradient70: yellow[700],
  bgYellowGradient50: yellow[500],
  bgVioletGradient70: violet[700],
  bgVioletGradient50: violet[500],
};

const surfaceDark = {
  bgNeutralPrimary: neutral[950],
  bgNeutralSecondary: neutral[850],
  bgNeutralTertiary: neutral[800],
  bgNeutralQuaternary: neutral[750],
  bgNeutralQuinary: neutral[700],
  bgNeutralSenary: neutral[600],
  bgNeutralGreyPrimary: neutral[800],
  bgNeutralGreyPrimaryTransparent: neutralOpacity[800.0],
  bgNeutralGreySecondary: neutral[850],
  bgNeutralGreyQuinary: neutral[800],
  bgNeutralGreyQuaternary: neutral[600],
  bgNeutralGreySenary: neutral[600],
  bgNeutralDark: neutral[750],
  bgTransparentPrimary: neutralOpacity[900.85],
  bgBaseScrollPrimary: neutralOpacity[950.0],
  bgBaseScrollSecondary: neutralOpacity[850.0],
  bgBaseScrollTertiary: neutralOpacity[800.0],
  bgBaseScrollNeutralBright: neutralOpacity[0.0],
  bgTransparentPrimaryBright: neutralOpacity[0.25],
  bgTransparentSecondaryBright: neutralOpacity[0.15],
  bgGreyPrimary: neutral[900],
  bgGreySecondary: neutral[200],
  bgGreyTertiary: neutral[500],
  bgGreyTransparentPrimary: neutralOpacity[200.2],
  bgGreyTransparentSecondary: neutralOpacity[200.3],
  bgButtonGroupNormal: neutral[800],
  bgButtonGroupPressed: neutralOpacity[600.25],
  bgOverlayBase: neutralOpacity[950.0],
  bgOverlayTop: neutralOpacity[850.85],
  bgOverlayBottom: neutralOpacity[950.95],
  bgOverlayGeneral: neutralOpacity[950.25],
  bgNeutralPositive: neutral[850],
  bgNeutralNegative: neutral[850],
  bgOrangePrimary: orange[500],
  bgOrangeSecondary: orange[900],
  bgOrangeTertiary: neutral[850],
  bgOrangeTransparentPrimary: orangeOpacity[500.2],
  bgOrangeTransparentSecondary: orangeOpacity[500.3],
  bgYellowPrimary: yellow[500],
  bgYellowSecondary: yellow[900],
  bgYellowTertiary: neutral[850],
  bgYellowTransparentPrimary: yellowOpacity[500.2],
  bgYellowTransparentSecondary: yellowOpacity[500.3],
  bgMintPrimary: mint[500],
  bgMintSecondary: mint[900],
  bgMintTertiary: neutral[850],
  bgMintTransparentPrimary: mintOpacity[500.2],
  bgMintTransparentSecondary: mintOpacity[500.3],
  bgBluePrimary: blue[500],
  bgBlueSecondary: blue[900],
  bgBlueTertiary: neutral[850],
  bgBlueTransparentPrimary: blueOpacity[500.2],
  bgBlueTransparentSecondary: blueOpacity[500.3],
  bgPurplePrimary: purple[500],
  bgPurpleSecondary: purple[900],
  bgPurpleTertiary: neutral[850],
  bgPurpleTransparentPrimary: purpleOpacity[500.2],
  bgPurpleTransparentSecondary: purpleOpacity[500.3],
  bgVioletPrimary: violet[500],
  bgVioletSecondary: violet[900],
  bgVioletTertiary: neutral[850],
  bgVioletTransparentPrimary: violetOpacity[500.2],
  bgVioletTransparentSecondary: violetOpacity[500.3],
  // TODO: change to liquid glass
  bgGlassPrimaryOverlay: neutralOpacity[950.25],

  bgDarkSurface: neutral[800],
  bgLightSurface: neutral[0],

  // gradients
  bgOrangeGradient70: orange[700],
  bgOrangeGradient50: orange[500],
  bgYellowGradient70: yellow[700],
  bgYellowGradient50: yellow[500],
  bgVioletGradient70: violet[700],
  bgVioletGradient50: violet[500],
};

export type SurfaceLight = typeof surfaceLight;
export type SurfaceDark = typeof surfaceDark;

export { surfaceDark, surfaceLight };
