// Auto-generated — do not edit manually
// Flags are loaded lazily via require() — only loaded when first requested
/* eslint-disable @typescript-eslint/no-require-imports */
import type { ComponentType } from 'react';
import type { SvgProps } from 'react-native-svg';

/** Lazy loaders — each flag SVG is only required when first accessed */
const flagLoaders = {
  ab: () => require('./svg/ab.svg').default,
  ad: () => require('./svg/ad.svg').default,
  ae: () => require('./svg/ae.svg').default,
  af: () => require('./svg/af.svg').default,
  ag: () => require('./svg/ag.svg').default,
  ai: () => require('./svg/ai.svg').default,
  al: () => require('./svg/al.svg').default,
  am: () => require('./svg/am.svg').default,
  an: () => require('./svg/an.svg').default,
  ao: () => require('./svg/ao.svg').default,
  aq: () => require('./svg/aq.svg').default,
  ar: () => require('./svg/ar.svg').default,
  as: () => require('./svg/as.svg').default,
  at: () => require('./svg/at.svg').default,
  au: () => require('./svg/au.svg').default,
  aw: () => require('./svg/aw.svg').default,
  ax: () => require('./svg/ax.svg').default,
  az: () => require('./svg/az.svg').default,
  azr: () => require('./svg/azr.svg').default,
  ba: () => require('./svg/ba.svg').default,
  bal: () => require('./svg/bal.svg').default,
  basq: () => require('./svg/basq.svg').default,
  bb: () => require('./svg/bb.svg').default,
  bcol: () => require('./svg/bcol.svg').default,
  bd: () => require('./svg/bd.svg').default,
  be: () => require('./svg/be.svg').default,
  bf: () => require('./svg/bf.svg').default,
  bg: () => require('./svg/bg.svg').default,
  bh: () => require('./svg/bh.svg').default,
  bi: () => require('./svg/bi.svg').default,
  bj: () => require('./svg/bj.svg').default,
  bl: () => require('./svg/bl.svg').default,
  bm: () => require('./svg/bm.svg').default,
  bn: () => require('./svg/bn.svg').default,
  bo: () => require('./svg/bo.svg').default,
  bq: () => require('./svg/bq.svg').default,
  br: () => require('./svg/br.svg').default,
  bs: () => require('./svg/bs.svg').default,
  bt: () => require('./svg/bt.svg').default,
  bv: () => require('./svg/bv.svg').default,
  bw: () => require('./svg/bw.svg').default,
  by: () => require('./svg/by.svg').default,
  bz: () => require('./svg/bz.svg').default,
  ca: () => require('./svg/ca.svg').default,
  caf: () => require('./svg/caf.svg').default,
  cc: () => require('./svg/cc.svg').default,
  cd: () => require('./svg/cd.svg').default,
  ceu: () => require('./svg/ceu.svg').default,
  cf: () => require('./svg/cf.svg').default,
  cg: () => require('./svg/cg.svg').default,
  ch: () => require('./svg/ch.svg').default,
  ci: () => require('./svg/ci.svg').default,
  ck: () => require('./svg/ck.svg').default,
  cl: () => require('./svg/cl.svg').default,
  cm: () => require('./svg/cm.svg').default,
  cn: () => require('./svg/cn.svg').default,
  cna: () => require('./svg/cna.svg').default,
  co: () => require('./svg/co.svg').default,
  coc: () => require('./svg/coc.svg').default,
  cr: () => require('./svg/cr.svg').default,
  cu: () => require('./svg/cu.svg').default,
  cv: () => require('./svg/cv.svg').default,
  cw: () => require('./svg/cw.svg').default,
  cx: () => require('./svg/cx.svg').default,
  cy: () => require('./svg/cy.svg').default,
  cz: () => require('./svg/cz.svg').default,
  de: () => require('./svg/de.svg').default,
  dj: () => require('./svg/dj.svg').default,
  dk: () => require('./svg/dk.svg').default,
  dm: () => require('./svg/dm.svg').default,
  do: () => require('./svg/do.svg').default,
  dz: () => require('./svg/dz.svg').default,
  ec: () => require('./svg/ec.svg').default,
  ee: () => require('./svg/ee.svg').default,
  eg: () => require('./svg/eg.svg').default,
  eh: () => require('./svg/eh.svg').default,
  eng: () => require('./svg/eng.svg').default,
  er: () => require('./svg/er.svg').default,
  es: () => require('./svg/es.svg').default,
  et: () => require('./svg/et.svg').default,
  eu: () => require('./svg/eu.svg').default,
  fi: () => require('./svg/fi.svg').default,
  fj: () => require('./svg/fj.svg').default,
  fk: () => require('./svg/fk.svg').default,
  fm: () => require('./svg/fm.svg').default,
  fo: () => require('./svg/fo.svg').default,
  fr: () => require('./svg/fr.svg').default,
  ga: () => require('./svg/ga.svg').default,
  gal: () => require('./svg/gal.svg').default,
  gb: () => require('./svg/gb.svg').default,
  gd: () => require('./svg/gd.svg').default,
  ge: () => require('./svg/ge.svg').default,
  gf: () => require('./svg/gf.svg').default,
  gg: () => require('./svg/gg.svg').default,
  gh: () => require('./svg/gh.svg').default,
  gi: () => require('./svg/gi.svg').default,
  gl: () => require('./svg/gl.svg').default,
  gm: () => require('./svg/gm.svg').default,
  gn: () => require('./svg/gn.svg').default,
  gp: () => require('./svg/gp.svg').default,
  gq: () => require('./svg/gq.svg').default,
  gr: () => require('./svg/gr.svg').default,
  gs: () => require('./svg/gs.svg').default,
  gt: () => require('./svg/gt.svg').default,
  gu: () => require('./svg/gu.svg').default,
  gw: () => require('./svg/gw.svg').default,
  gy: () => require('./svg/gy.svg').default,
  hi: () => require('./svg/hi.svg').default,
  hk: () => require('./svg/hk.svg').default,
  hm: () => require('./svg/hm.svg').default,
  hn: () => require('./svg/hn.svg').default,
  hr: () => require('./svg/hr.svg').default,
  ht: () => require('./svg/ht.svg').default,
  hu: () => require('./svg/hu.svg').default,
  id: () => require('./svg/id.svg').default,
  ie: () => require('./svg/ie.svg').default,
  il: () => require('./svg/il.svg').default,
  im: () => require('./svg/im.svg').default,
  in: () => require('./svg/in.svg').default,
  io: () => require('./svg/io.svg').default,
  iq: () => require('./svg/iq.svg').default,
  ir: () => require('./svg/ir.svg').default,
  is: () => require('./svg/is.svg').default,
  it: () => require('./svg/it.svg').default,
  je: () => require('./svg/je.svg').default,
  jm: () => require('./svg/jm.svg').default,
  jo: () => require('./svg/jo.svg').default,
  jp: () => require('./svg/jp.svg').default,
  ke: () => require('./svg/ke.svg').default,
  kg: () => require('./svg/kg.svg').default,
  kh: () => require('./svg/kh.svg').default,
  ki: () => require('./svg/ki.svg').default,
  km: () => require('./svg/km.svg').default,
  kn: () => require('./svg/kn.svg').default,
  kp: () => require('./svg/kp.svg').default,
  kr: () => require('./svg/kr.svg').default,
  kw: () => require('./svg/kw.svg').default,
  ky: () => require('./svg/ky.svg').default,
  kz: () => require('./svg/kz.svg').default,
  la: () => require('./svg/la.svg').default,
  lb: () => require('./svg/lb.svg').default,
  lc: () => require('./svg/lc.svg').default,
  li: () => require('./svg/li.svg').default,
  lk: () => require('./svg/lk.svg').default,
  lr: () => require('./svg/lr.svg').default,
  ls: () => require('./svg/ls.svg').default,
  lt: () => require('./svg/lt.svg').default,
  lu: () => require('./svg/lu.svg').default,
  lv: () => require('./svg/lv.svg').default,
  ly: () => require('./svg/ly.svg').default,
  ma: () => require('./svg/ma.svg').default,
  mad: () => require('./svg/mad.svg').default,
  mc: () => require('./svg/mc.svg').default,
  md: () => require('./svg/md.svg').default,
  me: () => require('./svg/me.svg').default,
  mel: () => require('./svg/mel.svg').default,
  mf: () => require('./svg/mf.svg').default,
  mg: () => require('./svg/mg.svg').default,
  mh: () => require('./svg/mh.svg').default,
  mk: () => require('./svg/mk.svg').default,
  ml: () => require('./svg/ml.svg').default,
  mm: () => require('./svg/mm.svg').default,
  mn: () => require('./svg/mn.svg').default,
  mo: () => require('./svg/mo.svg').default,
  mp: () => require('./svg/mp.svg').default,
  mq: () => require('./svg/mq.svg').default,
  mr: () => require('./svg/mr.svg').default,
  ms: () => require('./svg/ms.svg').default,
  mt: () => require('./svg/mt.svg').default,
  mu: () => require('./svg/mu.svg').default,
  mv: () => require('./svg/mv.svg').default,
  mw: () => require('./svg/mw.svg').default,
  mx: () => require('./svg/mx.svg').default,
  my: () => require('./svg/my.svg').default,
  mz: () => require('./svg/mz.svg').default,
  na: () => require('./svg/na.svg').default,
  nato: () => require('./svg/nato.svg').default,
  nc: () => require('./svg/nc.svg').default,
  ncy: () => require('./svg/ncy.svg').default,
  ne: () => require('./svg/ne.svg').default,
  nf: () => require('./svg/nf.svg').default,
  ng: () => require('./svg/ng.svg').default,
  ni: () => require('./svg/ni.svg').default,
  nl: () => require('./svg/nl.svg').default,
  no: () => require('./svg/no.svg').default,
  np: () => require('./svg/np.svg').default,
  nr: () => require('./svg/nr.svg').default,
  nu: () => require('./svg/nu.svg').default,
  nz: () => require('./svg/nz.svg').default,
  om: () => require('./svg/om.svg').default,
  ork: () => require('./svg/ork.svg').default,
  oss: () => require('./svg/oss.svg').default,
  pa: () => require('./svg/pa.svg').default,
  pe: () => require('./svg/pe.svg').default,
  pf: () => require('./svg/pf.svg').default,
  pg: () => require('./svg/pg.svg').default,
  ph: () => require('./svg/ph.svg').default,
  pk: () => require('./svg/pk.svg').default,
  pl: () => require('./svg/pl.svg').default,
  pm: () => require('./svg/pm.svg').default,
  pn: () => require('./svg/pn.svg').default,
  pr: () => require('./svg/pr.svg').default,
  ps: () => require('./svg/ps.svg').default,
  pt: () => require('./svg/pt.svg').default,
  pw: () => require('./svg/pw.svg').default,
  py: () => require('./svg/py.svg').default,
  qa: () => require('./svg/qa.svg').default,
  rap: () => require('./svg/rap.svg').default,
  re: () => require('./svg/re.svg').default,
  ro: () => require('./svg/ro.svg').default,
  rs: () => require('./svg/rs.svg').default,
  ru: () => require('./svg/ru.svg').default,
  rw: () => require('./svg/rw.svg').default,
  sa: () => require('./svg/sa.svg').default,
  sab: () => require('./svg/sab.svg').default,
  sar: () => require('./svg/sar.svg').default,
  sb: () => require('./svg/sb.svg').default,
  sc: () => require('./svg/sc.svg').default,
  sct: () => require('./svg/sct.svg').default,
  sd: () => require('./svg/sd.svg').default,
  se: () => require('./svg/se.svg').default,
  seu: () => require('./svg/seu.svg').default,
  sg: () => require('./svg/sg.svg').default,
  sh: () => require('./svg/sh.svg').default,
  si: () => require('./svg/si.svg').default,
  sj: () => require('./svg/sj.svg').default,
  sk: () => require('./svg/sk.svg').default,
  sl: () => require('./svg/sl.svg').default,
  sm: () => require('./svg/sm.svg').default,
  sn: () => require('./svg/sn.svg').default,
  so: () => require('./svg/so.svg').default,
  som: () => require('./svg/som.svg').default,
  sr: () => require('./svg/sr.svg').default,
  ss: () => require('./svg/ss.svg').default,
  st: () => require('./svg/st.svg').default,
  sv: () => require('./svg/sv.svg').default,
  sx: () => require('./svg/sx.svg').default,
  sy: () => require('./svg/sy.svg').default,
  sz: () => require('./svg/sz.svg').default,
  tc: () => require('./svg/tc.svg').default,
  td: () => require('./svg/td.svg').default,
  tf: () => require('./svg/tf.svg').default,
  tg: () => require('./svg/tg.svg').default,
  th: () => require('./svg/th.svg').default,
  tib: () => require('./svg/tib.svg').default,
  tj: () => require('./svg/tj.svg').default,
  tk: () => require('./svg/tk.svg').default,
  tl: () => require('./svg/tl.svg').default,
  tm: () => require('./svg/tm.svg').default,
  tn: () => require('./svg/tn.svg').default,
  tns: () => require('./svg/tns.svg').default,
  to: () => require('./svg/to.svg').default,
  tr: () => require('./svg/tr.svg').default,
  tt: () => require('./svg/tt.svg').default,
  tv: () => require('./svg/tv.svg').default,
  tw: () => require('./svg/tw.svg').default,
  tz: () => require('./svg/tz.svg').default,
  ua: () => require('./svg/ua.svg').default,
  ug: () => require('./svg/ug.svg').default,
  um: () => require('./svg/um.svg').default,
  un: () => require('./svg/un.svg').default,
  us: () => require('./svg/us.svg').default,
  uy: () => require('./svg/uy.svg').default,
  uz: () => require('./svg/uz.svg').default,
  va: () => require('./svg/va.svg').default,
  vc: () => require('./svg/vc.svg').default,
  ve: () => require('./svg/ve.svg').default,
  vg: () => require('./svg/vg.svg').default,
  vi: () => require('./svg/vi.svg').default,
  vn: () => require('./svg/vn.svg').default,
  vu: () => require('./svg/vu.svg').default,
  wal: () => require('./svg/wal.svg').default,
  wf: () => require('./svg/wf.svg').default,
  ws: () => require('./svg/ws.svg').default,
  xk: () => require('./svg/xk.svg').default,
  ye: () => require('./svg/ye.svg').default,
  yt: () => require('./svg/yt.svg').default,
  za: () => require('./svg/za.svg').default,
  zm: () => require('./svg/zm.svg').default,
  zw: () => require('./svg/zw.svg').default,
  zz: () => require('./svg/zz.svg').default,
};

/** All supported flag codes derived from the registry keys */
export type FlagCode = keyof typeof flagLoaders;

/** Cache for loaded flag components — filled on first access per flag */
const flagCache = new Map<string, ComponentType<SvgProps>>();

/**
 * Get a flag SVG component by code (lazy loaded).
 * Supports ISO 3166-1 alpha-2 country codes and non-ISO registry keys
 * (e.g., "nato", "un", "sct", "wal", "eng", "eu").
 *
 * @param isoCode - Country code or registry key (case-insensitive)
 * @returns The flag SVG component, or undefined if not found
 *
 * @example
 * const IsraelFlag = getFlagComponent('IL');
 * if (IsraelFlag) {
 *   return <IsraelFlag width={32} height={32} />;
 * }
 */
export function getFlagComponent(isoCode: string): ComponentType<SvgProps> | undefined {
  if (!isoCode?.trim()) return undefined;

  const key = isoCode.trim().toLowerCase();

  // Check cache
  const cached = flagCache.get(key);
  if (cached) return cached;

  // Load flag on first access
  const loader = flagLoaders[key as keyof typeof flagLoaders];
  if (!loader) return undefined;

  const component = loader();
  flagCache.set(key, component);
  return component;
}
