/**
 * Canonical list of icons from **DS — React** (Figma). Regenerated from SVG export.
 *
 * @see https://www.figma.com/design/cMyPhFndkPeXR6UkIuZujT/DS---React?node-id=37481-148641
 */

import { IconVariant } from '../api/types';

export interface DsReactIconSection {
  title: string;
  figmaNames: readonly string[];
}

export const DS_REACT_ICON_GALLERY = [
  {
    title: 'General',
    figmaNames: [
      'academy',
      'account',
      'add-card',
      'add-to-watchlist',
      'add-to-watchlist-1',
      'add-trade',
      'after-hours',
      'alert-circle',
      'alert-notification',
      'angle-down',
      'angle-down-small',
      'angle-left',
      'angle-left-small',
      'angle-right',
      'angle-right-small',
      'angle-up',
      'angle-up-small',
      'angles-up-down',
      'arrow-down',
      'arrow-down-left-small',
      'arrow-down-right-small',
      'arrow-left',
      'arrow-redo',
      'arrow-right',
      'arrow-right-left',
      'arrow-up',
      'arrow-up-left',
      'arrow-up-right',
      'arrows-collapessed',
      'arrows-expand',
      'arrows-repeat',
      'atm',
      'attach',
      'bank-payment',
      'bell-plus',
      'bell-ring',
      'block-account',
      'block-card',
      'bookmark',
      'bullhorn',
      'calendar',
      'camera',
      'cashflow-compensation',
      'cashflow-deposit',
      'cashflow-etoro-credit',
      'cashflow-withdrawal',
      'caret-down',
      'caret-fill-down',
      'caret-fill-up',
      'caret-up',
      'change-chart',
      'chart-candlestick-alt',
      'chart-column-alt',
      'chart-gradient',
      'chart-line',
      'chart-line-down',
      'chart-line-down-simple',
      'chart-line-gradient',
      'chart-line-simple',
      'chart-line-up',
      'chart-line-up-simple',
      'chart-pie',
      'chart-pie-simple',
      'chart-simple',
      'check',
      'check-circle',
      'clock',
      'close-trade',
      'columns',
      'comment',
      'compensation',
      'control',
      'copy',
      'coupon',
      'credit-card',
      'currency',
      'deposit-wallet',
      'direct-payment',
      'discover',
      'display',
      'display-desktop',
      'divident',
      'document',
      'dollar-sign',
      'easy-transfer',
      'edit',
      'edit-sltp',
      'email',
      'etoro-money',
      'exclamation',
      'eye',
      'eye-slash',
      'female',
      'filter',
      'filter-check',
      'folder',
      'freeze-card',
      'gear',
      'globe',
      'grid-square',
      'help',
      'home',
      'image',
      'in-app',
      'info-circle',
      'iphone',
      'jump-top',
      'key',
      'keyboard',
      'like',
      'limit-order',
      'link-horizontal',
      'location-pin',
      'lock',
      'logout',
      'male',
      'manage-workspace',
      'market-closed',
      'market-open',
      'market-order',
      'menu',
      'minus',
      'mobile',
      'money-in',
      'money-out',
      'more',
      'notification',
      'notification-1',
      'pen',
      'phone-incoming',
      'pin',
      'pin-code',
      'play',
      'play-circle',
      'plus',
      'plus-circle',
      'polls',
      'portfolio',
      'pre-market',
      'record-fill',
      'search',
      'search-1',
      'share',
      'share-payment',
      'shield',
      'smart-portfolio',
      'social',
      'sort',
      'sort-descending',
      'spam-flag',
      'spam-unflag',
      'star',
      'submit-document',
      'tag',
      'trash-simple',
      'unblock-account',
      'undo-freeze-card',
      'unlock',
      'unpin',
      'upload',
      'volume',
      'volume-slash',
      'watchlist',
      'xmark',
      'xmark-circle',
    ],
  },
] as const satisfies readonly DsReactIconSection[];

/** Every registry key from the latest SVG export (regular + filled + fill-only assets). */
export const DS_REACT_ICON_ALL_KEYS = [
  'academy',
  'account',
  'add-card',
  'add-to-watchlist',
  'add-to-watchlist-1',
  'add-trade',
  'add-trade-fill',
  'after-hours',
  'after-hours-fill',
  'alert-circle',
  'alert-circle-fill',
  'alert-notification',
  'alert-notification-fill',
  'angle-down',
  'angle-down-fill',
  'angle-down-small',
  'angle-down-small-fill',
  'angle-left',
  'angle-left-fill',
  'angle-left-small',
  'angle-left-small-fill',
  'angle-right',
  'angle-right-fill',
  'angle-right-small',
  'angle-right-small-fill',
  'angle-up',
  'angle-up-fill',
  'angle-up-small',
  'angle-up-small-fill',
  'angles-up-down',
  'angles-up-down-fill',
  'apple-fill',
  'arrow-down',
  'arrow-down-fill',
  'arrow-down-left-small',
  'arrow-down-left-small-fill',
  'arrow-down-right-small',
  'arrow-down-right-small-fill',
  'arrow-left',
  'arrow-left-fill',
  'arrow-redo',
  'arrow-redo-fill',
  'arrow-right',
  'arrow-right-fill',
  'arrow-right-left',
  'arrow-right-left-fill',
  'arrow-up',
  'arrow-up-fill',
  'arrow-up-left',
  'arrow-up-left-fill',
  'arrow-up-right',
  'arrow-up-right-fill',
  'arrows-collapessed',
  'arrows-expand',
  'arrows-expand-fill',
  'arrows-repeat',
  'arrows-repeat-fill',
  'atm',
  'attach',
  'bank-payment',
  'bank-payment-fill',
  'bell-plus',
  'bell-plus-fill',
  'bell-ring',
  'bell-ring-fill',
  'big-dot-fill',
  'block-account',
  'block-card',
  'bookmark',
  'bookmark-fill',
  'btc-fill',
  'bullhorn',
  'calendar',
  'calendar-fill',
  'camera',
  'camera-fill',
  'cashflow-compensation',
  'cashflow-deposit',
  'cashflow-etoro-credit',
  'cashflow-withdrawal',
  'caret-down',
  'caret-down-fill',
  'caret-fill-down',
  'caret-fill-up',
  'caret-up',
  'caret-up-fill',
  'change-chart',
  'change-chart-fill',
  'chart-candlestick-alt',
  'chart-candlestick-alt-fill',
  'chart-column-alt',
  'chart-column-alt-fill',
  'chart-gradient',
  'chart-line',
  'chart-line-down',
  'chart-line-down-fill',
  'chart-line-down-simple',
  'chart-line-down-simple-fill',
  'chart-line-fill',
  'chart-line-gradient',
  'chart-line-simple',
  'chart-line-simple-fill',
  'chart-line-up',
  'chart-line-up-fill',
  'chart-line-up-simple',
  'chart-line-up-simple-fill',
  'chart-pie',
  'chart-pie-fill',
  'chart-pie-simple',
  'chart-pie-simple-fill',
  'chart-simple',
  'chart-simple-fill',
  'check',
  'check-circle',
  'check-circle-fill',
  'check-fill',
  'clock',
  'clock-fill',
  'close-trade',
  'collapse-fill-left',
  'collapse-fill-right',
  'columns',
  'comment',
  'comment-fill',
  'compensation',
  'control',
  'copy',
  'copy-fill',
  'coupon',
  'credit-card',
  'credit-card-fill',
  'currency',
  'deposit-wallet',
  'deposit-wallet-fill',
  'direct-payment',
  'direct-payment-fill',
  'disconnected-fill',
  'discover',
  'discover-fill',
  'display',
  'display-desktop',
  'divident',
  'document',
  'dollar-sign',
  'dot-fill',
  'dot-fill-1',
  'drag-fill',
  'easy-transfer',
  'edit',
  'edit-sltp',
  'email',
  'etoro-fill',
  'etoro-money',
  'eur-fill',
  'exclamation',
  'exclamation-fill',
  'eye',
  'eye-fill',
  'eye-slash',
  'female',
  'filter',
  'filter-check',
  'filter-check-fill',
  'filter-fill',
  'folder',
  'folder-fill',
  'freeze-card',
  'gbp-fill',
  'gear',
  'gear-fill',
  'google-fill',
  'globe',
  'grid-square',
  'grid-square-fill',
  'help',
  'home',
  'home-fill',
  'image',
  'image-fill',
  'in-app',
  'info-circle',
  'info-fill',
  'iphone',
  'iphone-fill',
  'jump-top',
  'key',
  'keyboard',
  'keyboard-fill',
  'like',
  'like-fill',
  'limit-order',
  'link-horizontal',
  'location-pin',
  'location-pin-fill',
  'lock',
  'lock-fill',
  'logout',
  'male',
  'manage-workspace',
  'market-closed',
  'market-closed-fill',
  'market-open',
  'market-open-fill',
  'market-order',
  'menu',
  'meta-fill',
  'minus',
  'minus-fill',
  'mobile',
  'mobile-fill',
  'money-in',
  'money-out',
  'more',
  'notification',
  'notification-1',
  'notification-fill',
  'notification-fill-1',
  'pen',
  'pen-fill',
  'phone-incoming',
  'phone-incoming-fill',
  'pin',
  'pin-code',
  'pin-fill',
  'play',
  'play-circle',
  'play-circle-fill',
  'play-fill',
  'plus',
  'plus-circle',
  'plus-circle-fill',
  'plus-fill',
  'polls',
  'portfolio',
  'portfolio-fill',
  'pre-market',
  'pre-market-fill',
  'record-fill',
  'search',
  'search-1',
  'search-fill',
  'send-fill',
  'share',
  'share-fill',
  'share-payment',
  'share-payment-fill',
  'shield',
  'smart-portfolio',
  'social',
  'social-fill',
  'sort',
  'sort-descending',
  'sort-fill',
  'spam-flag',
  'spam-flag-fill',
  'spam-unflag',
  'sparkles-dark',
  'sparkles-light',
  'star',
  'star-fill',
  'submit-document',
  'tag',
  'tori-logo',
  'trash-simple',
  'trash-simple-fill',
  'unblock-account',
  'undo-freeze-card',
  'unlock',
  'unlock-fill',
  'unpin',
  'upload',
  'usd-fill',
  'volume',
  'volume-fill',
  'volume-slash',
  'volume-slash-fill',
  'watchlist',
  'watchlist-fill',
  'whats-app-fill',
  'write-fill',
  'xmark',
  'xmark-circle',
  'xmark-circle-fill',
  'xmark-fill',
] as const;

/** Icon names that appear on the main Figma “Regular” sheet only (from {@link DS_REACT_ICON_GALLERY}). */
export type DsReactGalleryIconName = (typeof DS_REACT_ICON_GALLERY)[number]['figmaNames'][number];

const DS_REACT_ICON_KEY_SET = new Set<string>([...DS_REACT_ICON_ALL_KEYS]);

function resolveFilledKeyFromRegularName(name: string): string | undefined {
  // Most exports follow `${name}-fill`
  const direct = `${name}-fill`;
  if (DS_REACT_ICON_KEY_SET.has(direct)) return direct;

  // Some exports insert `-fill-` before a numeric suffix, e.g. `notification-1` → `notification-fill-1`
  const numericSuffix = name.match(/^(.*)-(\d+)$/);
  if (numericSuffix) {
    const [, base, n] = numericSuffix;
    const candidate = `${base}-fill-${n}`;
    if (DS_REACT_ICON_KEY_SET.has(candidate)) return candidate;
  }

  // Some exports drop/replace a suffix, e.g. `info-circle` → `info-fill`
  const circleToFill = name.replace(/-circle$/, '-fill');
  if (circleToFill !== name && DS_REACT_ICON_KEY_SET.has(circleToFill)) return circleToFill;

  return undefined;
}

/**
 * Registry key for the Filled variant is derived from {@link DS_REACT_ICON_ALL_KEYS}.
 *
 * Most exports use `${regularName}-fill` (matches Figma export filenames, e.g. `trash-simple-fill.svg`),
 * but there are exceptions (e.g. `notification-1` → `notification-fill-1`, `info-circle` → `info-fill`).
 * Implemented SVGs are registered under that key in {@link DS_REACT_ICON_REGISTRY}.
 */
export function resolveDsReactRegistryName(name: string, variant: IconVariant): string {
  if (variant !== IconVariant.Filled) {
    return name;
  }
  // If a caller already passes a known filled key, keep it.
  if (DS_REACT_ICON_KEY_SET.has(name) && name.includes('fill')) {
    return name;
  }
  return resolveFilledKeyFromRegularName(name) ?? name;
}

/** Filled asset keys (as exported from the SVG bundle). */
export type DsReactFillOnlyName = Extract<DsReactIconName, `${string}fill${string}`>;

/** Any DS — React symbol name (matches keys in {@link DS_REACT_ICON_REGISTRY}). */
export type DsReactIconName = (typeof DS_REACT_ICON_ALL_KEYS)[number];

const DS_REACT_ICON_NAME_SET = DS_REACT_ICON_KEY_SET;

/** True when `name` is a symbol from the DS — React sheet (uses local registry / placeholder, not Zappicons CDN). */
export function isDsReactIconName(name: string): name is DsReactIconName {
  return DS_REACT_ICON_NAME_SET.has(name);
}
