import type { PhoneInputCountry } from './api';

// TODO: I yoinked this list from etoro-assets sign-up 'countries.ts'. We should move this to a shared config after the weekly Demos requested by Yoni :)
export const PHONE_INPUT_COUNTRIES: PhoneInputCountry[] = [
  {
    countryId: 1,
    name: 'Afghanistan',
    isoCode: 'AF',
    phonePrefix: '+93',
    riskGroupID: 3,
  },
  {
    countryId: 2,
    name: 'Albania',
    isoCode: 'AL',
    phonePrefix: '+355',
    riskGroupID: 2,
  },
  {
    countryId: 3,
    name: 'Algeria',
    isoCode: 'DZ',
    phonePrefix: '+213',
    riskGroupID: 3,
  },
  {
    countryId: 4,
    name: 'American Samoa',
    isoCode: 'AS',
    phonePrefix: '+1',
    riskGroupID: 1,
  },
  {
    countryId: 5,
    name: 'Andorra',
    isoCode: 'AD',
    phonePrefix: '+376',
    riskGroupID: 0,
  },
  {
    countryId: 6,
    name: 'Angola',
    isoCode: 'AO',
    phonePrefix: '+244',
    riskGroupID: 0,
  },
  {
    countryId: 7,
    name: 'Anguilla',
    isoCode: 'AI',
    phonePrefix: '+1',
    riskGroupID: 0,
  },
  {
    countryId: 8,
    name: 'Antigua and Barbuda',
    isoCode: 'AG',
    phonePrefix: '+1',
    riskGroupID: 0,
  },
  {
    countryId: 9,
    name: 'Argentina',
    isoCode: 'AR',
    phonePrefix: '+54',
    riskGroupID: 0,
  },
  {
    countryId: 10,
    name: 'Armenia',
    isoCode: 'AM',
    phonePrefix: '+374',
    riskGroupID: 0,
  },
  {
    countryId: 11,
    name: 'Aruba',
    isoCode: 'AW',
    phonePrefix: '+297',
    riskGroupID: 0,
  },
  {
    countryId: 12,
    name: 'Australia',
    isoCode: 'AU',
    phonePrefix: '+61',
    riskGroupID: 0,
  },
  {
    countryId: 13,
    name: 'Austria',
    isoCode: 'AT',
    phonePrefix: '+43',
    riskGroupID: 0,
  },
  {
    countryId: 14,
    name: 'Azerbaijan',
    isoCode: 'AZ',
    phonePrefix: '+994',
    riskGroupID: 0,
  },
  {
    countryId: 15,
    name: 'Bahrain',
    isoCode: 'BH',
    phonePrefix: '+973',
    riskGroupID: 0,
  },
  {
    countryId: 16,
    name: 'Bangladesh',
    isoCode: 'BD',
    phonePrefix: '+880',
    riskGroupID: 0,
  },
  {
    countryId: 17,
    name: 'Barbados',
    isoCode: 'BB',
    phonePrefix: '+1',
    riskGroupID: 0,
  },
  {
    countryId: 18,
    name: 'Belarus',
    isoCode: 'BY',
    phonePrefix: '+375',
    riskGroupID: 3,
  },
  {
    countryId: 19,
    name: 'Belgium',
    isoCode: 'BE',
    phonePrefix: '+32',
    riskGroupID: 0,
  },
  {
    countryId: 20,
    name: 'Belize',
    isoCode: 'BZ',
    phonePrefix: '+501',
    riskGroupID: 0,
  },
  {
    countryId: 21,
    name: 'Benin',
    isoCode: 'BJ',
    phonePrefix: '+229',
    riskGroupID: 0,
  },
  {
    countryId: 22,
    name: 'Bermuda',
    isoCode: 'BM',
    phonePrefix: '+1',
    riskGroupID: 0,
  },
  {
    countryId: 23,
    name: 'Bhutan',
    isoCode: 'BT',
    phonePrefix: '+975',
    riskGroupID: 0,
  },
  {
    countryId: 24,
    name: 'Bolivia',
    isoCode: 'BO',
    phonePrefix: '+591',
    riskGroupID: 0,
  },
  {
    countryId: 25,
    name: 'Bosnia and Herzegovina',
    isoCode: 'BA',
    phonePrefix: '+387',
    riskGroupID: 3,
  },
  {
    countryId: 26,
    name: 'Botswana',
    isoCode: 'BW',
    phonePrefix: '+267',
    riskGroupID: 0,
  },
  {
    countryId: 27,
    name: 'Bouvet Island',
    isoCode: 'BV',
    phonePrefix: '+47',
    riskGroupID: 0,
  },
  {
    countryId: 28,
    name: 'Brazil',
    isoCode: 'BR',
    phonePrefix: '+55',
    riskGroupID: 0,
  },
  {
    countryId: 29,
    name: 'Chagos Islands',
    isoCode: 'IO',
    phonePrefix: '+246',
    riskGroupID: 0,
  },
  {
    countryId: 30,
    name: 'Virgin Islands',
    isoCode: 'VG',
    phonePrefix: '+1',
    riskGroupID: 0,
  },
  {
    countryId: 31,
    name: 'Brunei',
    isoCode: 'BN',
    phonePrefix: '+673',
    riskGroupID: 0,
  },
  {
    countryId: 32,
    name: 'Bulgaria',
    isoCode: 'BG',
    phonePrefix: '+359',
    riskGroupID: 0,
  },
  {
    countryId: 33,
    name: 'Burkina Faso',
    isoCode: 'BF',
    phonePrefix: '+226',
    riskGroupID: 0,
  },
  {
    countryId: 34,
    name: 'Burundi',
    isoCode: 'BI',
    phonePrefix: '+257',
    riskGroupID: 0,
  },
  {
    countryId: 35,
    name: "Cote d'Ivoire",
    isoCode: 'CI',
    phonePrefix: '+225',
    riskGroupID: 0,
  },
  {
    countryId: 36,
    name: 'Cambodia',
    isoCode: 'KH',
    phonePrefix: '+855',
    riskGroupID: 0,
  },
  {
    countryId: 37,
    name: 'Cameroon',
    isoCode: 'CM',
    phonePrefix: '+237',
    riskGroupID: 0,
  },
  {
    countryId: 38,
    name: 'Canada',
    isoCode: 'CA',
    phonePrefix: '+1',
    riskGroupID: 1,
  },
  {
    countryId: 39,
    name: 'Cape Verde',
    isoCode: 'CV',
    phonePrefix: '+238',
    riskGroupID: 0,
  },
  {
    countryId: 40,
    name: 'Cayman Islands',
    isoCode: 'KY',
    phonePrefix: '+1',
    riskGroupID: 0,
  },
  {
    countryId: 41,
    name: 'CAR',
    isoCode: 'CF',
    phonePrefix: '+236',
    riskGroupID: 0,
  },
  {
    countryId: 42,
    name: 'Chad',
    isoCode: 'TD',
    phonePrefix: '+235',
    riskGroupID: 0,
  },
  {
    countryId: 43,
    name: 'Chile',
    isoCode: 'CL',
    phonePrefix: '+56',
    riskGroupID: 0,
  },
  {
    countryId: 44,
    name: 'China',
    isoCode: 'CN',
    phonePrefix: '+86',
    riskGroupID: 0,
  },
  {
    countryId: 45,
    name: 'Christmas Island',
    isoCode: 'CX',
    phonePrefix: '+61',
    riskGroupID: 0,
  },
  {
    countryId: 46,
    name: 'Cocos Islands',
    isoCode: 'CC',
    phonePrefix: '+891',
    riskGroupID: 0,
  },
  {
    countryId: 47,
    name: 'Colombia',
    isoCode: 'CO',
    phonePrefix: '+57',
    riskGroupID: 0,
  },
  {
    countryId: 48,
    name: 'Comoros',
    isoCode: 'KM',
    phonePrefix: '+269',
    riskGroupID: 0,
  },
  {
    countryId: 49,
    name: 'Congo',
    isoCode: 'CG',
    phonePrefix: '+242',
    riskGroupID: 0,
  },
  {
    countryId: 50,
    name: 'Cook Islands',
    isoCode: 'CK',
    phonePrefix: '+682',
    riskGroupID: 0,
  },
  {
    countryId: 51,
    name: 'Costa Rica',
    isoCode: 'CR',
    phonePrefix: '+506',
    riskGroupID: 0,
  },
  {
    countryId: 52,
    name: 'Croatia',
    isoCode: 'HR',
    phonePrefix: '+385',
    riskGroupID: 0,
  },
  {
    countryId: 53,
    name: 'Cuba',
    isoCode: 'CU',
    phonePrefix: '+53',
    riskGroupID: 1,
  },
  {
    countryId: 54,
    name: 'Cyprus',
    isoCode: 'CY',
    phonePrefix: '+357',
    riskGroupID: 4,
  },
  {
    countryId: 55,
    name: 'Czech Republic',
    isoCode: 'CZ',
    phonePrefix: '+420',
    riskGroupID: 0,
  },
  {
    countryId: 56,
    name: 'Congo Republic',
    isoCode: 'CD',
    phonePrefix: '+243',
    riskGroupID: 0,
  },
  {
    countryId: 57,
    name: 'Denmark',
    isoCode: 'DK',
    phonePrefix: '+45',
    riskGroupID: 0,
  },
  {
    countryId: 58,
    name: 'Djibouti',
    isoCode: 'DJ',
    phonePrefix: '+253',
    riskGroupID: 0,
  },
  {
    countryId: 59,
    name: 'Dominica',
    isoCode: 'DM',
    phonePrefix: '+1',
    riskGroupID: 0,
  },
  {
    countryId: 60,
    name: 'Dominican Republic',
    isoCode: 'DO',
    phonePrefix: '+1',
    riskGroupID: 0,
  },
  {
    countryId: 61,
    name: 'East Timor',
    isoCode: 'TL',
    phonePrefix: '+670',
    riskGroupID: 0,
  },
  {
    countryId: 62,
    name: 'Ecuador',
    isoCode: 'EC',
    phonePrefix: '+593',
    riskGroupID: 0,
  },
  {
    countryId: 63,
    name: 'Egypt',
    isoCode: 'EG',
    phonePrefix: '+20',
    riskGroupID: 0,
  },
  {
    countryId: 64,
    name: 'El Salvador',
    isoCode: 'SV',
    phonePrefix: '+503',
    riskGroupID: 0,
  },
  {
    countryId: 65,
    name: 'Equatorial Guinea',
    isoCode: 'GQ',
    phonePrefix: '+240',
    riskGroupID: 0,
  },
  {
    countryId: 66,
    name: 'Eritrea',
    isoCode: 'ER',
    phonePrefix: '+291',
    riskGroupID: 0,
  },
  {
    countryId: 67,
    name: 'Estonia',
    isoCode: 'EE',
    phonePrefix: '+372',
    riskGroupID: 0,
  },
  {
    countryId: 68,
    name: 'Ethiopia',
    isoCode: 'ET',
    phonePrefix: '+251',
    riskGroupID: 3,
  },
  {
    countryId: 69,
    name: 'Faeroe Islands',
    isoCode: 'FO',
    phonePrefix: '+298',
    riskGroupID: 0,
  },
  {
    countryId: 70,
    name: 'Falkland Islands',
    isoCode: 'FK',
    phonePrefix: '+500',
    riskGroupID: 0,
  },
  {
    countryId: 71,
    name: 'Fiji',
    isoCode: 'FJ',
    phonePrefix: '+679',
    riskGroupID: 0,
  },
  {
    countryId: 72,
    name: 'Finland',
    isoCode: 'FI',
    phonePrefix: '+358',
    riskGroupID: 0,
  },
  {
    countryId: 73,
    name: 'Macedonia',
    isoCode: 'MK',
    phonePrefix: '+389',
    riskGroupID: 0,
  },
  {
    countryId: 74,
    name: 'France',
    isoCode: 'FR',
    phonePrefix: '+33',
    riskGroupID: 0,
  },
  {
    countryId: 75,
    name: 'French Polynesia',
    isoCode: 'PF',
    phonePrefix: '+689',
    riskGroupID: 0,
  },
  {
    countryId: 76,
    name: 'French Southern',
    isoCode: 'TF',
    phonePrefix: '+594',
    riskGroupID: 0,
  },
  {
    countryId: 77,
    name: 'Gabon',
    isoCode: 'GA',
    phonePrefix: '+241',
    riskGroupID: 0,
  },
  {
    countryId: 78,
    name: 'Georgia',
    isoCode: 'GE',
    phonePrefix: '+995',
    riskGroupID: 0,
  },
  {
    countryId: 79,
    name: 'Germany',
    isoCode: 'DE',
    phonePrefix: '+49',
    riskGroupID: 0,
  },
  {
    countryId: 80,
    name: 'Ghana',
    isoCode: 'GH',
    phonePrefix: '+233',
    riskGroupID: 0,
  },
  {
    countryId: 81,
    name: 'Gibraltar',
    isoCode: 'GI',
    phonePrefix: '+350',
    riskGroupID: 0,
  },
  {
    countryId: 82,
    name: 'Greece',
    isoCode: 'GR',
    phonePrefix: '+30',
    riskGroupID: 0,
  },
  {
    countryId: 83,
    name: 'Greenland',
    isoCode: 'GL',
    phonePrefix: '+299',
    riskGroupID: 0,
  },
  {
    countryId: 84,
    name: 'Grenada',
    isoCode: 'GD',
    phonePrefix: '+1',
    riskGroupID: 0,
  },
  {
    countryId: 85,
    name: 'Guadeloupe',
    isoCode: 'GP',
    phonePrefix: '+590',
    riskGroupID: 0,
  },
  {
    countryId: 86,
    name: 'Guam',
    isoCode: 'GU',
    phonePrefix: '+1',
    riskGroupID: 1,
  },
  {
    countryId: 87,
    name: 'Guatemala',
    isoCode: 'GT',
    phonePrefix: '+502',
    riskGroupID: 0,
  },
  {
    countryId: 88,
    name: 'Guinea',
    isoCode: 'GN',
    phonePrefix: '+224',
    riskGroupID: 0,
  },
  {
    countryId: 89,
    name: 'Guinea-Bissau',
    isoCode: 'GW',
    phonePrefix: '+245',
    riskGroupID: 0,
  },
  {
    countryId: 90,
    name: 'Guyana',
    isoCode: 'GY',
    phonePrefix: '+592',
    riskGroupID: 3,
  },
  {
    countryId: 91,
    name: 'Haiti',
    isoCode: 'HT',
    phonePrefix: '+509',
    riskGroupID: 0,
  },
  {
    countryId: 92,
    name: 'Honduras',
    isoCode: 'HN',
    phonePrefix: '+504',
    riskGroupID: 0,
  },
  {
    countryId: 93,
    name: 'Hong Kong',
    isoCode: 'HK',
    phonePrefix: '+852',
    riskGroupID: 0,
  },
  {
    countryId: 94,
    name: 'Hungary',
    isoCode: 'HU',
    phonePrefix: '+36',
    riskGroupID: 0,
  },
  {
    countryId: 95,
    name: 'Iceland',
    isoCode: 'IS',
    phonePrefix: '+354',
    riskGroupID: 0,
  },
  {
    countryId: 96,
    name: 'India',
    isoCode: 'IN',
    phonePrefix: '+91',
    riskGroupID: 0,
  },
  {
    countryId: 97,
    name: 'Indonesia',
    isoCode: 'ID',
    phonePrefix: '+62',
    riskGroupID: 0,
  },
  {
    countryId: 98,
    name: 'Iran',
    isoCode: 'IR',
    phonePrefix: '+98',
    riskGroupID: 1,
  },
  {
    countryId: 99,
    name: 'Iraq',
    isoCode: 'IQ',
    phonePrefix: '+964',
    riskGroupID: 3,
  },
  {
    countryId: 100,
    name: 'Ireland',
    isoCode: 'IE',
    phonePrefix: '+353',
    riskGroupID: 0,
  },
  {
    countryId: 101,
    name: 'Israel',
    isoCode: 'IL',
    phonePrefix: '+972',
    riskGroupID: 3,
  },
  {
    countryId: 102,
    name: 'Italy',
    isoCode: 'IT',
    phonePrefix: '+39',
    riskGroupID: 0,
  },
  {
    countryId: 103,
    name: 'Jamaica',
    isoCode: 'JM',
    phonePrefix: '+1',
    riskGroupID: 0,
  },
  {
    countryId: 104,
    name: 'Japan',
    isoCode: 'JP',
    phonePrefix: '+81',
    riskGroupID: 2,
  },
  {
    countryId: 105,
    name: 'Jordan',
    isoCode: 'JO',
    phonePrefix: '+962',
    riskGroupID: 0,
  },
  {
    countryId: 106,
    name: 'Kazakhstan',
    isoCode: 'KZ',
    phonePrefix: '+7',
    riskGroupID: 0,
  },
  {
    countryId: 107,
    name: 'Kenya',
    isoCode: 'KE',
    phonePrefix: '+254',
    riskGroupID: 0,
  },
  {
    countryId: 108,
    name: 'Kiribati',
    isoCode: 'KI',
    phonePrefix: '+686',
    riskGroupID: 0,
  },
  {
    countryId: 109,
    name: 'Kuwait',
    isoCode: 'KW',
    phonePrefix: '+965',
    riskGroupID: 0,
  },
  {
    countryId: 110,
    name: 'Kyrgyzstan',
    isoCode: 'KG',
    phonePrefix: '+996',
    riskGroupID: 0,
  },
  {
    countryId: 111,
    name: 'Laos',
    isoCode: 'LA',
    phonePrefix: '+856',
    riskGroupID: 3,
  },
  {
    countryId: 112,
    name: 'Latvia',
    isoCode: 'LV',
    phonePrefix: '+371',
    riskGroupID: 0,
  },
  {
    countryId: 113,
    name: 'Lebanon',
    isoCode: 'LB',
    phonePrefix: '+961',
    riskGroupID: 3,
  },
  {
    countryId: 114,
    name: 'Lesotho',
    isoCode: 'LS',
    phonePrefix: '+266',
    riskGroupID: 0,
  },
  {
    countryId: 115,
    name: 'Liberia',
    isoCode: 'LR',
    phonePrefix: '+231',
    riskGroupID: 0,
  },
  {
    countryId: 116,
    name: 'Libya',
    isoCode: 'LY',
    phonePrefix: '+218',
    riskGroupID: 0,
  },
  {
    countryId: 117,
    name: 'Liechtenstein',
    isoCode: 'LI',
    phonePrefix: '+423',
    riskGroupID: 0,
  },
  {
    countryId: 118,
    name: 'Lithuania',
    isoCode: 'LT',
    phonePrefix: '+370',
    riskGroupID: 0,
  },
  {
    countryId: 119,
    name: 'Luxembourg',
    isoCode: 'LU',
    phonePrefix: '+352',
    riskGroupID: 0,
  },
  {
    countryId: 120,
    name: 'Macau',
    isoCode: 'MO',
    phonePrefix: '+853',
    riskGroupID: 0,
  },
  {
    countryId: 121,
    name: 'Madagascar',
    isoCode: 'MG',
    phonePrefix: '+261',
    riskGroupID: 0,
  },
  {
    countryId: 122,
    name: 'Malawi',
    isoCode: 'MW',
    phonePrefix: '+265',
    riskGroupID: 0,
  },
  {
    countryId: 123,
    name: 'Malaysia',
    isoCode: 'MY',
    phonePrefix: '+60',
    riskGroupID: 0,
  },
  {
    countryId: 124,
    name: 'Maldives',
    isoCode: 'MV',
    phonePrefix: '+960',
    riskGroupID: 0,
  },
  {
    countryId: 125,
    name: 'Mali',
    isoCode: 'ML',
    phonePrefix: '+223',
    riskGroupID: 0,
  },
  {
    countryId: 126,
    name: 'Malta',
    isoCode: 'MT',
    phonePrefix: '+356',
    riskGroupID: 0,
  },
  {
    countryId: 127,
    name: 'Marshall Islands',
    isoCode: 'MH',
    phonePrefix: '+692',
    riskGroupID: 0,
  },
  {
    countryId: 128,
    name: 'Martinique',
    isoCode: 'MQ',
    phonePrefix: '+596',
    riskGroupID: 0,
  },
  {
    countryId: 129,
    name: 'Mauritania',
    isoCode: 'MR',
    phonePrefix: '+222',
    riskGroupID: 0,
  },
  {
    countryId: 130,
    name: 'Mauritius',
    isoCode: 'MU',
    phonePrefix: '+230',
    riskGroupID: 0,
  },
  {
    countryId: 131,
    name: 'Mayotte',
    isoCode: 'YT',
    phonePrefix: '+269',
    riskGroupID: 0,
  },
  {
    countryId: 132,
    name: 'Mexico',
    isoCode: 'MX',
    phonePrefix: '+52',
    riskGroupID: 0,
  },
  {
    countryId: 133,
    name: 'Micronesia',
    isoCode: 'FM',
    phonePrefix: '+691',
    riskGroupID: 0,
  },
  {
    countryId: 134,
    name: 'Moldova',
    isoCode: 'MD',
    phonePrefix: '+373',
    riskGroupID: 0,
  },
  {
    countryId: 135,
    name: 'Monaco',
    isoCode: 'MC',
    phonePrefix: '+377',
    riskGroupID: 0,
  },
  {
    countryId: 136,
    name: 'Mongolia',
    isoCode: 'MN',
    phonePrefix: '+976',
    riskGroupID: 0,
  },
  {
    countryId: 137,
    name: 'Montserrat',
    isoCode: 'MS',
    phonePrefix: '+1',
    riskGroupID: 0,
  },
  {
    countryId: 138,
    name: 'Morocco',
    isoCode: 'MA',
    phonePrefix: '+212',
    riskGroupID: 0,
  },
  {
    countryId: 139,
    name: 'Mozambique',
    isoCode: 'MZ',
    phonePrefix: '+258',
    riskGroupID: 0,
  },
  {
    countryId: 140,
    name: 'Myanmar',
    isoCode: 'MM',
    phonePrefix: '+95',
    riskGroupID: 0,
  },
  {
    countryId: 141,
    name: 'Namibia',
    isoCode: 'NA',
    phonePrefix: '+264',
    riskGroupID: 1,
  },
  {
    countryId: 142,
    name: 'Nauru',
    isoCode: 'NR',
    phonePrefix: '+674',
    riskGroupID: 0,
  },
  {
    countryId: 143,
    name: 'Netherlands',
    isoCode: 'NL',
    phonePrefix: '+31',
    riskGroupID: 0,
  },
  {
    countryId: 144,
    name: 'Netherlands Antilles',
    isoCode: 'AN',
    phonePrefix: '+599',
    riskGroupID: 0,
  },
  {
    countryId: 145,
    name: 'New Caledonia',
    isoCode: 'NC',
    phonePrefix: '+687',
    riskGroupID: 0,
  },
  {
    countryId: 146,
    name: 'New Zealand',
    isoCode: 'NZ',
    phonePrefix: '+64',
    riskGroupID: 2,
  },
  {
    countryId: 147,
    name: 'Nicaragua',
    isoCode: 'NI',
    phonePrefix: '+505',
    riskGroupID: 0,
  },
  {
    countryId: 148,
    name: 'Niger',
    isoCode: 'NE',
    phonePrefix: '+227',
    riskGroupID: 0,
  },
  {
    countryId: 149,
    name: 'Nigeria',
    isoCode: 'NG',
    phonePrefix: '+234',
    riskGroupID: 0,
  },
  {
    countryId: 150,
    name: 'Niue',
    isoCode: 'NU',
    phonePrefix: '+683',
    riskGroupID: 0,
  },
  {
    countryId: 151,
    name: 'Norfolk Island',
    isoCode: 'NF',
    phonePrefix: '+672',
    riskGroupID: 0,
  },
  {
    countryId: 152,
    name: 'North Korea',
    isoCode: 'KP',
    phonePrefix: '+850',
    riskGroupID: 1,
  },
  {
    countryId: 153,
    name: 'Northern Marianas',
    isoCode: 'MP',
    phonePrefix: '+1',
    riskGroupID: 1,
  },
  {
    countryId: 154,
    name: 'Norway',
    isoCode: 'NO',
    phonePrefix: '+47',
    riskGroupID: 0,
  },
  {
    countryId: 155,
    name: 'Oman',
    isoCode: 'OM',
    phonePrefix: '+968',
    riskGroupID: 0,
  },
  {
    countryId: 156,
    name: 'Pakistan',
    isoCode: 'PK',
    phonePrefix: '+92',
    riskGroupID: 3,
  },
  {
    countryId: 157,
    name: 'Palau',
    isoCode: 'PW',
    phonePrefix: '+680',
    riskGroupID: 1,
  },
  {
    countryId: 158,
    name: 'Panama',
    isoCode: 'PA',
    phonePrefix: '+507',
    riskGroupID: 0,
  },
  {
    countryId: 159,
    name: 'Papua New Guinea',
    isoCode: 'PG',
    phonePrefix: '+675',
    riskGroupID: 0,
  },
  {
    countryId: 160,
    name: 'Paraguay',
    isoCode: 'PY',
    phonePrefix: '+595',
    riskGroupID: 0,
  },
  {
    countryId: 161,
    name: 'Peru',
    isoCode: 'PE',
    phonePrefix: '+51',
    riskGroupID: 0,
  },
  {
    countryId: 162,
    name: 'Philippines',
    isoCode: 'PH',
    phonePrefix: '+63',
    riskGroupID: 0,
  },
  {
    countryId: 163,
    name: 'Pitcairn Islands',
    isoCode: 'PN',
    phonePrefix: '+870',
    riskGroupID: 0,
  },
  {
    countryId: 164,
    name: 'Poland',
    isoCode: 'PL',
    phonePrefix: '+48',
    riskGroupID: 0,
  },
  {
    countryId: 165,
    name: 'Portugal',
    isoCode: 'PT',
    phonePrefix: '+351',
    riskGroupID: 0,
  },
  {
    countryId: 166,
    name: 'Puerto Rico',
    isoCode: 'PR',
    phonePrefix: '+1',
    riskGroupID: 1,
  },
  {
    countryId: 167,
    name: 'Qatar',
    isoCode: 'QA',
    phonePrefix: '+974',
    riskGroupID: 0,
  },
  {
    countryId: 168,
    name: 'Romania',
    isoCode: 'RO',
    phonePrefix: '+40',
    riskGroupID: 0,
  },
  {
    countryId: 169,
    name: 'Russia',
    isoCode: 'RU',
    phonePrefix: '+7',
    riskGroupID: 0,
  },
  {
    countryId: 170,
    name: 'Rwanda',
    isoCode: 'RW',
    phonePrefix: '+250',
    riskGroupID: 0,
  },
  {
    countryId: 171,
    name: 'Saint Vincent',
    isoCode: 'VC',
    phonePrefix: '+1',
    riskGroupID: 0,
  },
  {
    countryId: 172,
    name: 'Saint Helena',
    isoCode: 'SH',
    phonePrefix: '+290',
    riskGroupID: 0,
  },
  {
    countryId: 173,
    name: 'Saint Kitts and Nevis',
    isoCode: 'KN',
    phonePrefix: '+1',
    riskGroupID: 0,
  },
  {
    countryId: 174,
    name: 'Saint Lucia',
    isoCode: 'LC',
    phonePrefix: '+1',
    riskGroupID: 0,
  },
  {
    countryId: 175,
    name: 'South Georgia',
    isoCode: 'GS',
    phonePrefix: '+508',
    riskGroupID: 0,
  },
  {
    countryId: 176,
    name: 'Turks and Caicos Islands',
    isoCode: 'TC',
    phonePrefix: '+1',
    riskGroupID: 0,
  },
  {
    countryId: 177,
    name: 'Samoa',
    isoCode: 'WS',
    phonePrefix: '+685',
    riskGroupID: 1,
  },
  {
    countryId: 178,
    name: 'San Marino',
    isoCode: 'SM',
    phonePrefix: '+378',
    riskGroupID: 0,
  },
  {
    countryId: 179,
    name: 'Saudi Arabia',
    isoCode: 'SA',
    phonePrefix: '+966',
    riskGroupID: 0,
  },
  {
    countryId: 180,
    name: 'Senegal',
    isoCode: 'SN',
    phonePrefix: '+221',
    riskGroupID: 0,
  },
  {
    countryId: 181,
    name: 'Seychelles',
    isoCode: 'SC',
    phonePrefix: '+248',
    riskGroupID: 0,
  },
  {
    countryId: 182,
    name: 'Sierra Leone',
    isoCode: 'SL',
    phonePrefix: '+232',
    riskGroupID: 0,
  },
  {
    countryId: 183,
    name: 'Singapore',
    isoCode: 'SG',
    phonePrefix: '+65',
    riskGroupID: 0,
  },
  {
    countryId: 184,
    name: 'Slovakia',
    isoCode: 'SK',
    phonePrefix: '+421',
    riskGroupID: 0,
  },
  {
    countryId: 185,
    name: 'Slovenia',
    isoCode: 'SI',
    phonePrefix: '+386',
    riskGroupID: 0,
  },
  {
    countryId: 186,
    name: 'Solomon Islands',
    isoCode: 'SB',
    phonePrefix: '+677',
    riskGroupID: 0,
  },
  {
    countryId: 187,
    name: 'Somalia',
    isoCode: 'SO',
    phonePrefix: '+252',
    riskGroupID: 0,
  },
  {
    countryId: 188,
    name: 'South Africa',
    isoCode: 'ZA',
    phonePrefix: '+27',
    riskGroupID: 0,
  },
  {
    countryId: 189,
    name: 'US Minor Islands',
    isoCode: 'UM',
    phonePrefix: '+1',
    riskGroupID: 1,
  },
  {
    countryId: 190,
    name: 'South Korea',
    isoCode: 'KR',
    phonePrefix: '+82',
    riskGroupID: 0,
  },
  {
    countryId: 191,
    name: 'Spain',
    isoCode: 'ES',
    phonePrefix: '+34',
    riskGroupID: 0,
  },
  {
    countryId: 192,
    name: 'Sri Lanka',
    isoCode: 'LK',
    phonePrefix: '+94',
    riskGroupID: 3,
  },
  {
    countryId: 193,
    name: 'Sudan',
    isoCode: 'SD',
    phonePrefix: '+249',
    riskGroupID: 1,
  },
  {
    countryId: 194,
    name: 'Suriname',
    isoCode: 'SR',
    phonePrefix: '+597',
    riskGroupID: 0,
  },
  {
    countryId: 195,
    name: 'Swaziland',
    isoCode: 'SZ',
    phonePrefix: '+268',
    riskGroupID: 0,
  },
  {
    countryId: 196,
    name: 'Sweden',
    isoCode: 'SE',
    phonePrefix: '+46',
    riskGroupID: 0,
  },
  {
    countryId: 197,
    name: 'Switzerland',
    isoCode: 'CH',
    phonePrefix: '+41',
    riskGroupID: 0,
  },
  {
    countryId: 198,
    name: 'Syria',
    isoCode: 'SY',
    phonePrefix: '+963',
    riskGroupID: 1,
  },
  {
    countryId: 199,
    name: 'Taiwan',
    isoCode: 'TW',
    phonePrefix: '+886',
    riskGroupID: 0,
  },
  {
    countryId: 200,
    name: 'Tajikistan',
    isoCode: 'TJ',
    phonePrefix: '+992',
    riskGroupID: 0,
  },
  {
    countryId: 201,
    name: 'Tanzania',
    isoCode: 'TZ',
    phonePrefix: '+255',
    riskGroupID: 0,
  },
  {
    countryId: 202,
    name: 'Thailand',
    isoCode: 'TH',
    phonePrefix: '+66',
    riskGroupID: 0,
  },
  {
    countryId: 203,
    name: 'Bahamas',
    isoCode: 'BS',
    phonePrefix: '+1',
    riskGroupID: 0,
  },
  {
    countryId: 204,
    name: 'Gambia',
    isoCode: 'GM',
    phonePrefix: '+220',
    riskGroupID: 0,
  },
  {
    countryId: 205,
    name: 'Togo',
    isoCode: 'TG',
    phonePrefix: '+228',
    riskGroupID: 0,
  },
  {
    countryId: 206,
    name: 'Tokelau',
    isoCode: 'TK',
    phonePrefix: '+690',
    riskGroupID: 0,
  },
  {
    countryId: 207,
    name: 'Tonga',
    isoCode: 'TO',
    phonePrefix: '+676',
    riskGroupID: 0,
  },
  {
    countryId: 208,
    name: 'Trinidad and Tobago',
    isoCode: 'TT',
    phonePrefix: '+1',
    riskGroupID: 3,
  },
  {
    countryId: 209,
    name: 'Tunisia',
    isoCode: 'TN',
    phonePrefix: '+216',
    riskGroupID: 3,
  },
  {
    countryId: 210,
    name: 'Turkey',
    isoCode: 'TR',
    phonePrefix: '+90',
    riskGroupID: 2,
  },
  {
    countryId: 211,
    name: 'Turkmenistan',
    isoCode: 'TM',
    phonePrefix: '+993',
    riskGroupID: 0,
  },
  {
    countryId: 212,
    name: 'Heard Island',
    isoCode: 'HM',
    phonePrefix: '+1',
    riskGroupID: 0,
  },
  {
    countryId: 213,
    name: 'Tuvalu',
    isoCode: 'TV',
    phonePrefix: '+688',
    riskGroupID: 0,
  },
  {
    countryId: 214,
    name: 'US Virgin Islands',
    isoCode: 'VI',
    phonePrefix: '+1',
    riskGroupID: 1,
  },
  {
    countryId: 215,
    name: 'Uganda',
    isoCode: 'UG',
    phonePrefix: '+256',
    riskGroupID: 3,
  },
  {
    countryId: 216,
    name: 'Ukraine',
    isoCode: 'UA',
    phonePrefix: '+380',
    riskGroupID: 0,
  },
  {
    countryId: 217,
    name: 'United Arab Emirates',
    isoCode: 'AE',
    phonePrefix: '+971',
    riskGroupID: 0,
  },
  {
    countryId: 218,
    name: 'United Kingdom',
    isoCode: 'GB',
    phonePrefix: '+44',
    riskGroupID: 0,
  },
  {
    countryId: 219,
    name: 'United States',
    isoCode: 'US',
    phonePrefix: '+1',
    riskGroupID: 0,
  },
  {
    countryId: 220,
    name: 'Saint Pierre',
    isoCode: 'PM',
    phonePrefix: '+508',
    riskGroupID: 0,
  },
  {
    countryId: 221,
    name: 'Uruguay',
    isoCode: 'UY',
    phonePrefix: '+598',
    riskGroupID: 0,
  },
  {
    countryId: 222,
    name: 'Uzbekistan',
    isoCode: 'UZ',
    phonePrefix: '+998',
    riskGroupID: 0,
  },
  {
    countryId: 223,
    name: 'Vanuatu',
    isoCode: 'VU',
    phonePrefix: '+678',
    riskGroupID: 3,
  },
  {
    countryId: 224,
    name: 'Vatican City',
    isoCode: 'VA',
    phonePrefix: '+379',
    riskGroupID: 0,
  },
  {
    countryId: 225,
    name: 'Venezuela',
    isoCode: 'VE',
    phonePrefix: '+58',
    riskGroupID: 0,
  },
  {
    countryId: 226,
    name: 'Vietnam',
    isoCode: 'VN',
    phonePrefix: '+84',
    riskGroupID: 0,
  },
  {
    countryId: 227,
    name: 'Wallis and Futuna',
    isoCode: 'WF',
    phonePrefix: '+681',
    riskGroupID: 0,
  },
  {
    countryId: 228,
    name: 'Islands',
    isoCode: 'EH',
    phonePrefix: '+212',
    riskGroupID: 0,
  },
  {
    countryId: 229,
    name: 'Yemen',
    isoCode: 'YE',
    phonePrefix: '+967',
    riskGroupID: 3,
  },
  {
    countryId: 230,
    name: 'Zambia',
    isoCode: 'ZM',
    phonePrefix: '+260',
    riskGroupID: 0,
  },
  {
    countryId: 231,
    name: 'Zimbabwe',
    isoCode: 'ZW',
    phonePrefix: '+263',
    riskGroupID: 0,
  },
  {
    countryId: 232,
    name: 'Sao Tome',
    isoCode: 'ST',
    phonePrefix: '+239',
    riskGroupID: 0,
  },
  {
    countryId: 233,
    name: 'Jersey Island',
    isoCode: 'JE',
    phonePrefix: '+44',
    riskGroupID: 0,
  },
  {
    countryId: 234,
    name: 'Nepal',
    isoCode: 'NP',
    phonePrefix: '+977',
    riskGroupID: 0,
  },
  {
    countryId: 235,
    name: 'Palestinian Territory',
    isoCode: 'PS',
    phonePrefix: '+970',
    riskGroupID: 0,
  },
  {
    countryId: 236,
    name: 'Reunion Island',
    isoCode: 'RE',
    phonePrefix: '+262',
    riskGroupID: 0,
  },
  {
    countryId: 237,
    name: 'Serbia',
    isoCode: 'RS',
    phonePrefix: '+381',
    riskGroupID: 2,
  },
  {
    countryId: 238,
    name: 'Montenegro',
    isoCode: 'ME',
    phonePrefix: '+382',
    riskGroupID: 0,
  },
  {
    countryId: 239,
    name: 'Antarctica',
    isoCode: 'AQ',
    phonePrefix: '+672',
    riskGroupID: 0,
  },
  {
    countryId: 240,
    name: 'Svalbard and Jan Mayen',
    isoCode: 'SJ',
    phonePrefix: '+47',
    riskGroupID: 0,
  },
  {
    countryId: 241,
    name: 'French Guiana',
    isoCode: 'GF',
    phonePrefix: '+594',
    riskGroupID: 0,
  },
  {
    countryId: 242,
    name: 'Guernsey',
    isoCode: 'GG',
    phonePrefix: '+44',
    riskGroupID: 0,
  },
  {
    countryId: 243,
    name: 'Aland Islands',
    isoCode: 'AX',
    phonePrefix: '+672',
    riskGroupID: 0,
  },
  {
    countryId: 244,
    name: 'Isle Of Man',
    isoCode: 'IM',
    phonePrefix: '+44',
    riskGroupID: 0,
  },
  {
    countryId: 245,
    name: 'Bonaire',
    isoCode: 'BQ',
    phonePrefix: '+599',
    riskGroupID: 0,
  },
  {
    countryId: 246,
    name: 'Curacao',
    isoCode: 'CW',
    phonePrefix: '+599',
    riskGroupID: 0,
  },
  {
    countryId: 247,
    name: 'Saint Barthelemy',
    isoCode: 'BL',
    phonePrefix: '+590',
    riskGroupID: 0,
  },
  {
    countryId: 248,
    name: 'Saint Martin',
    isoCode: 'MF',
    phonePrefix: '+599',
    riskGroupID: 0,
  },
  {
    countryId: 249,
    name: 'Sint Maarten (Dutch Part)',
    isoCode: 'SX',
    phonePrefix: '+590',
    riskGroupID: 0,
  },
  {
    countryId: 250,
    name: 'eToro',
    isoCode: 'ZZ',
    phonePrefix: '+972',
    riskGroupID: 0,
  },
] as const;
